### ISSUE TITLE
Import workflow into Dockstore

### ISSUE THREAD

**Issue by deflaux** [jump-cellpainting/embedder#11]
@shntnu can you please make this repo public so that we can import it into Dockstore? It will eventually look something like https://dockstore.org/workflows/github.com/broadinstitute/cellprofiler-on-Terra/cellprofiler:v0.3.0?tab=info

**Comment by shntnu** [comment]
@deflaux nice to hear from you! All set

**Comment by deflaux** [comment]
https://docs.dockstore.org/en/stable/advanced-topics/best-practices/wdl-best-practices.html

**Comment by deflaux** [comment]
@shntnu the workflow is in Dockstore in my own GitHub org https://dockstore.org/workflows/github.com/deflaux/embedder:main?tab=info but it would be better if it were in GitHub org [thub.com/orgs/jump-cellpainting/packages](https://github.com/jump-cellpainting)

Does that sound good to you? If "yes" I'm happy to publish it there, if I have permission. Or see [how to publish](https://docs.dockstore.org/en/stable/getting-started/dockstore-workflows.html#register-your-workflow-to-automatically-sync-with-github-recommended).

**Comment by shntnu** [comment]
> Does that sound good to you?

replied in https://github.com/jump-cellpainting/embedder/issues/12#issuecomment-2104419330

**Comment by deflaux** [comment]
@shntnu I believe Dockstore sent a request to you for this repo. I should be able to set up the workflow after you take care of the request.

**Comment by shntnu** [comment]
> @shntnu I believe Dockstore sent a request to you for this repo. I should be able to set up the workflow after you take care of the request.

All set 🚀

**Comment by deflaux** [comment]
I just gave it a try, but got error "This action must be performed by an organization owner". 

See https://docs.dockstore.org/en/stable/getting-started/dockstore-workflows.html#register-your-workflow-to-automatically-sync-with-github-recommended if you want to take care of it instead of giving me that level of access. Thanks!

**Comment by shntnu** [comment]
Ah ok

I got this notification below and approved it; would that suffice?


> 
> ---------- Forwarded message ---------
> From: JUMP-Cell Painting Consortium <noreply@github.com>
> Date: Fri, May 10, 2024 at 7:11 PM
> Subject: [GitHub] Third-party application approval request for "JUMP-Cell Painting Consortium"
> To: Shantanu Singh <shsingh@broadinstitute.org>
> 
> 
> @deflaux has requested approval for a third-party application to access "JUMP-Cell Painting Consortium" organization resources via the GitHub API:
> 
>   "Dockstore" from Dockstore
> 
> Until it is approved, this application will have no access to private resources and will have read-only access to public resources belonging to your organization.
> 
> You may approve or deny this request here:
> 
>   https://github.com/orgs/jump-cellpainting/policies/applications/256763
> 
> Learn more about organization application access policies in this GitHub Help article:
> 
>   https://docs.github.com/organizations/managing-oauth-access-to-your-organizations-data/about-oauth-app-access-restrictions
> 

Status on https://github.com/orgs/jump-cellpainting/policies/applications/256763:

<img width="991" alt="image" src="https://github.com/jump-cellpainting/embedder/assets/1210428/8cf6000b-7f19-41db-bff5-e0e1802b9599">

**Comment by deflaux** [comment]
Almost. Dockstore still needs to be enabled for the specific repository. I tried it again and I got the same permission error. Here's the link https://github.com/apps/dockstore/installations/50601425 Are you able to select repo `jump-cellpainting/embedder`? Thank you @shntnu !!

**Comment by shntnu** [comment]
> Are you able to select repo `jump-cellpainting/embedder`?

Hm that was already selected

I have made you an owner 🎉 so hopefully that will unblock you now

**Comment by deflaux** [comment]
All set now!! https://dockstore.org/workflows/github.com/jump-cellpainting/embedder:main?tab=info

You can remove my org access now @shntnu, thank you!!
