### ISSUE TITLE
Push Docker image to a public place

### ISSUE THREAD

**Issue by deflaux** [jump-cellpainting/embedder#12]
Note that this will require a manual build and push since the public image will start from the image used to create the embeddings back in 2022 and 2023.

@shntnu and @dmikeando any opinions on the name for the public Docker image for this method?

**Comment by deflaux** [comment]
https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images

**Comment by deflaux** [comment]
@shntnu the public Docker image is currently in my own GitHub org https://github.com/deflaux?tab=packages but it would be better if it were here https://github.com/orgs/jump-cellpainting/packages

Does that sound good to you? If "yes" I'm happy to publish it there, if I have permission. Or see [how to publish](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#pushing-container-images).

**Comment by shntnu** [comment]
> any opinions on the name for the public Docker image for this method?

how about `cell-painting-embedder`?


> @shntnu the public Docker image is currently in my own GitHub org https://github.com/deflaux?tab=packages 

Hooray!


> but it would be better if it were here https://github.com/orgs/jump-cellpainting/packages
> Does that sound good to you? If "yes" I'm happy to publish it there, if I have permission. 

Yes, please proceed and please let me know if you don't have permissions

**Comment by deflaux** [comment]
That worked fine! https://github.com/orgs/jump-cellpainting/packages
